name: Qt 自动编译打包 (macOS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13  # 👈 这个才是能正常打包的 Intel 环境

    steps:
      - uses: actions/checkout@v5

      # 安装系统依赖 + 修复Python
      - name: 安装依赖
        run: |
          python3 -m pip install py7zr setuptools --break-system-packages

      # 安装 Qt
      - name: 安装 Qt 6.6.2
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.2'
          host: mac
          target: desktop
          arch: clang_64
          setup-python: false
          modules: qtwebsockets

      # 编译（通用二进制：Intel + M 芯片）
      - name: 编译项目
        run: |
          mkdir build
          cd build
          qmake ../qt_im_project_macOS.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64"
          make

      # 复制资源
      - name: 复制资源文件
        run: |
          cp -r btnimage build/qt_im_project.app/Contents/Resources/

      # 🔥 关键：真正完整打包 Qt 依赖
      - name: 打包成 dmg
        run: |
          cd build
          macdeployqt qt_im_project.app -dmg -always-overwrite

      # 上传
      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: Qt_IM_Project_macOS
          path: build/*.dmg